spring:
      datasource:
                url: jdbc:mysql://localhost:3306/springbootcrud
                driver-class-name: com.mysql.cj.jdbc.Driver
                username: root
                password: yaswanth@123
      jpa:
         hibernate:
           ddl-auto: update
         show-sql: true
         properties:
           hibernate:
             dialect: org.hibernate.dialect.MySQL5Dialect 
